#!/usr/bin/env ruby
# set_xp <filename> <new_xp> - sets the XP of the character
# xp is stored in two bytes, little endian, at bytes 0xAC-0xAD

require_relative 'poolrad'
id = ARGV[0]
new_xp = ARGV[1].to_i

poolrad = Poolrad.new
poolrad.assert_game_configuration!
poolrad.assert_save_game_exists! id

get_xp = File.join(poolrad.here, 'get_xp')
puts `#{get_xp} #{id}`

poolrad.backup_savegame! id

filename = poolrad.save_filepath(id)

data = File.open(filename, "rb").read
name = data[1..15].unpack1("A*")

puts "Setting #{name}'s XP to #{ARGV[1]}..."
data[172..175] = [new_xp].pack("L")

File.open(filename, "wb") do |fp|
  fp.write data
end

puts `#{get_xp} #{id}`.sub(/currently/, 'now')
