* Things To Do In Skyrim [0/2]
- [ ] Find out if it is possible to ally with the Thalmor (e.g. play as Altmer)
- [ ] Find a pretty argonians mod? Almost certainly! NexusMods is 90% T&A
  anyway.

** Dawnguard-Specific [1/2]
- [X] Find out: is it possible to marry Serana? TL;DR No. Longer: yes, with
  mods, but Serana has a custom, unique voice actress and there are no voice
  assets for the standard marriage lines, so she'll either be mute or her voice
  will be replaced with the standard Breton Female. So you can make Serana wait
  at your house and give you coin for running a store and such, but you'll never
  hear Laura Bailey voice act the line "Welcome home, my love." *wistful sigh*
- [ ] As a vampire lord, you can turn your spouse into a vampire. They won't get
  red eyes but they'll develop a bit of a snarl or split lip, and supposedly
  argonians will develop a full-face split.
  - [ ] Marry an argonian (Shahvee is the only candidate w/o mods) and vampirize
    her just to see what it's like
