require 'rake/testtask'

Rake::TestTask.new(:test) do |t|
  t.libs << 'test'
  t.libs << 'lib'
  t.test_files = FileList['test/**/*_test.rb']
end

task all: %i[rubocop test]

task :rubocop do
  sh 'rubocop -DS'
end

task default: :all
